# Generated by roxytest: Do not edit by hand!
# Last updated: 2019-10-22 14:16:27

context("File R/functions.R"")

test_that("Function foo() @ L10", {
  expect_equal(foo(2), sqrt(2))
  expect_error(foo("a string"))
})


test_that("Function bar() @ L23", {
  expect_equal(bar("A", "B"), paste("A", "B", sep = "/"))
})

