# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-09 20:23:05

context("File R/functions.R: @testexamples")

test_that("Function foo2() @ L66", {
  
  x <- 2
  foo(x)
  
  expect_equal(foo(x), foo(2))
})

