# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-05-09 20:23:05

# File R/functions.R: @tests

## Function foo() @ L10
expect_equal(foo(2), sqrt(2))
expect_error(foo("a string"))


## Function bar() @ L26
expect_equal(bar("A", "B"), paste("A", "B", sep = "/"))


## Function foo2() @ L66
expect_equal(foo(2), sqrt(2))
expect_error(foo("a string"))

